title: I'm Chetan Parthiban!
description: > # this means to ignore newlines until "baseurl:"
  Check out some of my awesome recent projects here or connect with me via social media at the bottom! 
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "chetan-parthiban.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Chetan Parthiban # add your name
author-img: imageedit_2_5732612583.gif # add your photo
about-author: >
  I am a teaching assistant for MSSP 608 at the University of Pennsylvania! 
  Currently looking for internships. <a href="chetan-parthiban-github.io/assets/cv.pdf">Check out my cv.</a> # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: chetan-parthiban # add your Github handle
social-linkedin: chetan-parthiban # add your Linkedin handle
social-email: chetanp@sas.upenn.edu# add your Email address

# Disqus
discus-identifier: Chetan # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
